### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Zazus** [NicosaurusRex99/bugs-Cake-Factory#3]
https://gist.github.com/anonymous/e3dcf80aa8b00b9ce3a0024c0eb73cff

**Comment by NicosaurusRex99** [comment]
I am aware of this bug, currently waiting on a fix from an author so please downgrade your version to 1.17D

**Comment by NicosaurusRex99** [comment]
After reading again its not the initial bug i thought but the downgrade should work!

**Comment by NicosaurusRex99** [comment]
@Zazus is this on a server?!? Spigot or bukkit?!? or just in singleplayer?

**Comment by NicosaurusRex99** [comment]
https://github.com/skyboy/MineFactoryReloaded/issues/600 @Zazus this sounds like that issue
